### PR TITLE
C# Taste Of Riak Examples

### PR DESCRIPTION
**Pull request by lukebakken**
Ch03 has C#-specific goodness.

### CODE REVIEW

**Comment by alexmoore** [comment]
We should reference the riak client nuget package.

**Comment by lukebakken** [comment]
@alexmoore it is already. Did you see something else?

**Comment by alexmoore** [comment]
My bad, I'm used to the solution-level packages.config file.

**Comment by alexmoore** [comment]
Only thing I don't like is the `public string GetMsgKey(uint index)` method. Could probably change it's usage to `MsgKeys.First();`. Looks like pretty good enterprise grade c# otherwise.  :+1:

**Comment by lukebakken** [comment]
Thanks! I'll be merging this soon after one more re-test of each chapter.

**Pull request merged**
